# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define :fedora34 do |f34|
    f34.vm.box = "generic/fedora34"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup_ansible_user.yml"
  end
end
