---
- name: Update the whole system
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install extra packages and applications
  dnf:
    name: "{{ extra_packages }}"
    state: present

- name: Remove nano-default-editor
  dnf:
    name: nano-default-editor
    state: absent

- name: Set vim as default editor
  dnf:
    name: vim-default-editor
    state: present

- name: Autoremove unneded packages installed as dependencies
  dnf:
    autoremove: yes
