---
# Enable RPM Fusion repos
- name: Get Fedora version
  command: 'rpm -E %fedora'
  register: fedora_version
  changed_when: false

- name: Enable RPM Fusion (free and nonfree) repos
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm"
    state: present
    disable_gpg_check: yes

# Disable unnecessary repos and machine counting
- name: Disable unwanted repos
  lineinfile:
    path: "/etc/yum.repos.d/{{ item }}"
    regexp: '^enabled=1'
    line: enabled=0
  with_items:
    - fedora-updates-modular.repo
    - fedora-modular.repo
    - fedora-updates-testing-modular.repo
    - rpmfusion-free-updates-testing.repo
    - fedora-cisco-openh264.repo

- name: Get a list of .repo files
  find:
    paths: /etc/yum.repos.d
    patterns: "*.repo"
  register: repo_list

- name: Disable machine counting for all repos
  replace:
    path: "{{ item.path }}"
    regexp: '^countme=1'
    replace: 'countme=0'
  with_items: "{{ repo_list.files }}"
